# Configuração Global
global:

  evaluation_interval: 15s 

scrape_configs:

  - job_name: node_exporter
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.5:9100"]

  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.3:8080"]

  - job_name: monitor_script
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.6:8085"]

