# Configuração Global
global:
  evaluation_interval: 15s 

scrape_configs:

  - job_name: node_exporter
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["172.18.0.2:9100"]

  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["172.18.0.3:8080"]

